[package]
name = "kafkaesque"
version = "0.1.0"
authors = ["Frank McSherry <fmcsherry@me.com>"]

[dependencies]
clap="*"
abomonation="0.7"
timely= { git = "https://github.com/TimelyDataflow/timely-dataflow" }

[dependencies.rdkafka]
version = "0.14.0"
